
////////////////////////////////////////////////////////////////////////////////

   // HC11-SPECIFIC ERRORS

   ERROR_INTVECT_SCI,
   ERROR_INTVECT_SPI,
   ERROR_INTVECT_PAIE,
   ERROR_INTVECT_PAO,
   ERROR_INTVECT_TOF,
   ERROR_INTVECT_TOC5,
   ERROR_INTVECT_TOC4,
   ERROR_INTVECT_TOC3,
   ERROR_INTVECT_TOC2,
   ERROR_INTVECT_TOC1,
   ERROR_INTVECT_TIC3,
   ERROR_INTVECT_TIC2,
   ERROR_INTVECT_TIC1,
   ERROR_INTVECT_RTI,
   ERROR_INTVECT_IRQ,
   ERROR_INTVECT_XIRQ,
   ERROR_INTVECT_SWI,
   ERROR_INTVECT_COP,
   ERROR_INTVECT_ILLOP,
   ERROR_INTVECT_CLM,
   ERROR_INTVECT_RESET,
   ERROR_INTVECT_OTHER,

////////////////////////////////////////////////////////////////////////////////


